titleText ["Air Transport Tutorial", "BLACK FADED", 0.5];
hint "Welcome to the Air Transport Tutorial";
sleep 4.0;
hint "Use your radio at any time to call in air transport. 0->8->4->1.";
sleep 5.0;
hint "LAST ONE ON AND OFF: You must order your team to board the chopper before boarding the chopper yourself. Press ~ to select your whole team, place your cursor over the chopper, and order your team to board via the action menu";
sleep 12.0;
hint "TELLING YOUR PILOT WHERE TO GO: You must order the chopper's destination from the map (press 'M'). Once you get on the chopper (make sure you are the last one on) an option to set chopper destination will automatically appear as the sole action available";
sleep 12.0;
hint "WARNING: YOU CANNOT CANCEL OUT OF THE SELECT DESTINATION INTERFACE ONCE IT HAS OPENED! IF YOU DO YOU WILL NEED TO DISEMBARK AND ORDER THE CHOPPER TO LAND AGAIN VIA 0->8->4->1!";
sleep 15.0;
hint "Select the location on the map and click or press ENTER while your cursor is hovering over the area you want your chopper to land. This should ONLY be done from the map interface (Press M) immediately after you board the chopper as the last man. Your chopper will fly to the target you set on the map.";
sleep 15.0;
hint "You have two different chopper teams you can request. Combat air 5 is a blackhawk escorted by a littlebird. Air 22 is a Camo blackhawk, is faster, but unescorted. Air 22 is better for transport into stealth insertions or when resistance is not expected. Combat Air 5 is for hot, CAS insertions."; 
sleep 12.0;
hint "This concludes the air transport tutorial, You may launch this tutorial again by using radio 'alpha' for a limited time. (Just press 0 for radio and select tutorialtrg).";
HP1 setTaskState "Succeeded";
Player setCurrentTask AAF1;
saveGame;